### ISSUE TITLE
Require support for Large Message quality for Commands

### ISSUE THREAD

**Issue by pidarped** [project-chip/alchemy#11]
The Large Message `L` quality was introduced for commands that have a large payload(beyond the MRP capacity). Alchemy needs to incorporate this into its xml generation to, potentially, generate something like:
```
    <command id="0x01" name="WebRTCOffer" direction="commandToServer" response="Y">
      <quality largeMessage="true"/>
```

**Comment by pidarped** [comment]
ZAP PR(by Dhruv from the ZAP team) for Large message quality support: https://github.com/project-chip/zap/pull/1467

**Comment by hasty** [comment]
Supported in 0.9.4 release
