### ISSUE TITLE
Alchemy should do better at determining command descriptions

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/alchemy#4]
In https://github.com/project-chip/connectedhomeip/pull/34517, the diff has weirdly truncated command descriptions, including at least one where the entire description in the XML is "ID".

Whatever Alchemy is doing here, hopefully it can do better.  Once it can, that XML file should be fixed.

**Comment by bzbarsky-apple** [comment]
Specifically, see https://github.com/project-chip/connectedhomeip/pull/34517#discussion_r1695385282

**Comment by hasty** [comment]
Fixed in [0.6.1](https://github.com/project-chip/alchemy/releases/tag/v0.6.1)
